# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160319_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
